### ISSUE TITLE
HomeWork for next week 

### ISSUE THREAD

**Issue by AlexandreGazagnes** [Nada-Lahbib/Project-10#2]
## Todo
- [x] Accept #1 
- [x] GIT PULL !!!!!!!!!!!!!!
- [x] Add GNU GPLv3 license
- [x] Add Standard default .gitignore 
- [x] Light update of README.md
- [x] Continue data exploration => matrice corr / recherche ouliers /  pair plot hue is genuine / pie plot plot target ...
- [x] 1st WORK => IMPUTE NAN VALUES
    - how ? => using a linear regression ! 
    - **with scikit learn (first)** and statsmodels (second)
